/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Cinewulf (https://sketchfab.com/Cinewulf)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/study-island-of-monkeys-terrain-test-96cd84cf9f954b2eaee59bcb7e898f8b
Title: study: Island of Monkeys terrain test
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF } from '@react-three/drei'
import{ useFrame, useThree } from '@react-three/fiber'
import { a } from '@react-spring/three'

import islandScene from '../assets/study_island_of_monkeys_terrain_test.glb';

export function Island(props) {
const islandRef = useRef();
  const { nodes, materials } = useGLTF(islandScene);
  return (
    <a.group {...props} dispose={null}>
      <group scale={[1, 1, 0.875]}>
        <mesh geometry={nodes.Object_6.geometry} material={materials['MonkeyIsland.001']} />
        <mesh geometry={nodes.Object_7.geometry} material={materials['MonkeyIsland.001']} />
        <mesh geometry={nodes.Object_8.geometry} material={materials['MonkeyIsland.001']} />
        <mesh geometry={nodes.Object_9.geometry} material={materials['MonkeyIsland.001']} />
        <mesh geometry={nodes.Object_10.geometry} material={materials['MonkeyIsland.001']} />
      </group>
      <mesh
        geometry={nodes.Object_4.geometry}
        material={materials['Material.001']}
        position={[-356.393, -11.833, 312.83]}
        scale={[1, 1, 0.875]}
      />
    </a.group>
  )
}

export default Island;